apiVersion: apps.openliberty.io/v1beta2
kind: OpenLibertyApplication
metadata:
  namespace: nhs-app-ibkhdn
  name: ebank-corp
  labels:
    app: ebank-corp
spec:
  expose: true
  resources:
    limits:
      cpu: 4000m
      memory: 4Gi
      ephemeral-storage: 20Gi
    requests:
      cpu: 1000m
      memory: 2Gi
      ephemeral-storage: 20Gi
  autoscaling:
    maxReplicas: 3
    minReplicas: 2
    targetCPUUtilizationPercentage: 70    
  replicas: 2
  applicationImage: quay.io/dtduong/ebank-corp:1.0.7
  pullPolicy: Always
  applicationName: ebank-corp
  env:
    - name: DB_PASSWORD_ENCRYPT
      value: "true"
    - name: DB_CONNECTION
      value: "jdbc:oracle:thin:@10.0.35.162:1521/khdn"
    - name: DB_USER
      value: "khdn"
    - name: DB_PASS
      value: "Mvi7heVtiV72hynN3NLzOg==****"
    - name: retailURL
      value: "https://ebank-corp.apps-ext.ocp4-dev03.pvcomtestocp.com/IBSRetail/"
    - name: corpURL
      value: "https://digitalcorp.pvcombank.com.vn/"
    - name: adminURL
      value: "https://ebank-admin.apps.aws-southeast-prod01.pvcombank.io/"
    - name: OTPControl
      value: "open"
    - name: UrlGateWay
      value: "http://esb.pvcb.vn:8081/IBRestService/system"
    - name: UrlAuthGateWay
      value: "http://mfa.pvcb.vn"
    - name: UrlPrivateKey
      value: "signature/privateKeyEBANK_UAT.key"
    - name: UrlPublicKey
      value: "signature/publicKeyEBANK_UAT.pub"
    - name: UrlCheckRule
      value: "http://ebank-transaction-rule-check-nhs-app-ibkhdn-uat.apps.ocp4-dev03.pvcomtestocp.com/ebank-transaction-rule-check/checkRule"
    - name: CheckTransRuleAPI
      value: "true"
    - name: RequestType_API
      value: "prod"
    - name: FolderLogTimeFormat
      value: "dd-MM-yyyy"
    - name: UrlBillingTopUpGateWay
      value: "http://10.0.25.73:8080/PGService/outwardservice"
    - name: BillingTopUpWrapper
      value: "http://pgservice.pvcombank.com.vn"
    - name: host
      value: "http://esb.pvcb.vn:8081"
    - name: hostSMS
      value: "http://10.0.25.79:8080"
    - name: linkPointVN
      value: "https://www.pvcombank.com.vn/san-pham/ca-nhan/dich-vu-the/the-pvcombank-mastercard-platinum"
    - name: linkPointEN
      value: "https://www.pvcombank.com.vn/san-pham/ca-nhan/dich-vu-the/the-pvcombank-mastercard-platinum"
    - name: APICheckLogin
      value: "N"
    - name: EnableSMSOTP
      value: "N"
    - name: isCheckOTP
      value: "false"
    - name: KafkaBootstrpServers
      value: "k8kafka.pvcb.vn:9094"
    - name: KafkaTopic
      value: "prod.notification.sendmail.1"
    - name: IPAuthSecret
      value: "lTBLKPwTWd4/sxLNOE41/opMN5XvoOcUmnak8XB+vCA=****"
    - name: IPAuthExpiredMilisec
      value: "86400000"
    - name: IPAuthSecretEncrypted
      value: "true"

