apiVersion: apps.openliberty.io/v1beta2
kind: OpenLibertyApplication
metadata:
  namespace: ebank-pvcb
  name: ebank-corp
spec:
  expose: true
  resources:
    limits:
      cpu: 4000m
      memory: 4096Mi
    requests:
      memory: 1024Mi
      cpu: 500m
  applicationVersion: 1.0.0
  applicationImage: quay.io/dtduong/ebank-corp:1.0.0
  env:
    - name: DB_CONNECTION
      value: "jdbc:oracle:thin:@192.168.1.89:1521/ebank"
    - name: DB_USER
      value: "test"
    - name: DB_PASS
      value: "test"
    - name: retailURL
      value: "http://103.121.91.49:9091/IBSRetail/"
    - name: corpURL
      value: "https://103.121.91.49/IBSCorporate/"
    - name: adminURL
      value: "https://103.121.91.49/IBSAdmin/"
    - name: corpMobileURL
      value: "https://103.121.91.49/IBS-Corporate-Mobile-Server/"
    - name: OTPControl
      value: "open"
    - name: UrlGateWay
      value: "http://103.121.91.49:8081/IBRestService/system"
    - name: UrlAuthGateWay
      value: "hhttp://103.121.91.49:8083"
    - name: UrlPrivateKey
      value: "signature/privateKeyIDVN_UAT.key"
    - name: UrlPublicKey
      value: "signature/publicKeyIDVN_UAT.pub"
    - name: UrlCheckRule
      value: "http://192.168.1.209:9099/IBS-TransactionRule-Check/checkRule"
    - name: CheckTransRuleAPI
      value: "true"
    - name: RequestType_API
      value: "prod"
    - name: FolderLogTimeFormat
      value: "dd-MM-yyyy"
    - name: UrlBillingTopUpGateWay
      value: "http://103.121.91.49:8087/PGService/outwardservice"
    - name: BillingTopUpWrapper
      value: "http://pgservice.pvcombank.com.vn"
    - name: host
      value: "http://103.121.91.49:8081"
    - name: hostSMS
      value: "http://103.121.91.49:8089"
    - name: linkPointVN
      value: "https://www.pvcombank.com.vn/san-pham/ca-nhan/dich-vu-the/the-pvcombank-mastercard-platinum"
    - name: linkPointEN
      value: "https://www.pvcombank.com.vn/san-pham/ca-nhan/dich-vu-the/the-pvcombank-mastercard-platinum"
    - name: APICheckLogin
      value: "N"
    - name: EnableSMSOTP
      value: "N"
    - name: isCheckOTP
      value: "false"      
  pullPolicy: Always
  replicas: 1
  applicationName: ebank-corp
